name: Update Fuel Data
on:
  repository_dispatch:
    types: [cron_trigger]
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python Script
        # ดึง Secret จาก GitHub มายัดใส่ Environment Variable ให้ Python มองเห็น
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: python main.py

      - name: Commit and Push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update data.json"
          git push
